plf/main/urls.py
from django.conf.urls import patterns, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

patterns = urlpatterns = patterns(
    '',
    url(r'^invitation/(?P<token>[a-zA-Z0-9]{32})', 'main.views.invitation', name='invitation'),
    url(r'^reset/(?P<token>[a-zA-Z0-9]{32})',    'main.views.reset', name='reset'),
    url(r'^recover/$',    'main.views.recover', name='recover'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'main/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^debug/$', 'main.views.debug'),
)

plf/plf/urls.py
from django.conf.urls import patterns, include, url

# static
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^albums/', include('photocms.urls', namespace="photocms")),
    url(r'^boards/', include('boards.urls', namespace="boards")),
    url(r'^plf/', include('main.urls', namespace="main")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', RedirectView.as_view(url=reverse_lazy('photocms:list')), name='front'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plf/main/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User

from uuidfield import UUIDField


class Token(models.Model):
    id = UUIDField(auto=True, primary_key=True)
    tag = models.CharField(max_length=128, blank=False, null=False, default=None)
    lifetime = models.IntegerField(default=60*60*24)
    created = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return u"%s %s" % (self.tag, self.id)

    @property
    def namespace(self):
        return '.'.join(self.tag.split('.')[:-1])

    @property
    def locator(self):
        return self.tag.split('.')[-1]

    def get_absolute_url(self):
        urlname = ':'.join(self.tag.split('.')[0:2])
        return reverse(urlname, args=[self.id])

    def is_valid(self):
        return True

plf/main/forms.py
import re
from django import forms
from django.db.models import Q
from main.models import User


def _validate_password_pair(cleaned_data, p1, p2):
    p1v = cleaned_data.get(p1)
    p2v = cleaned_data.get(p2)
    return (p1v == p2v)


class InvitationForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    token = forms.CharField(widget=forms.HiddenInput)

    def clean_username(self):
        value = self.cleaned_data.get('username')
        if not re.match(r'^[a-z0-9\.\-_ ]+$', value):
            raise forms.ValidationError("Username must contain only lowercase letters, numbers, '.', '-', '_' and spaces")
        if not User.objects.filter(username=value).exists():
            return value.lower()
        else:
            raise forms.ValidationError("This username is already taken")

    def clean(self):
        cleaned_data = super(InvitationForm, self).clean()
        if not _validate_password_pair(cleaned_data, 'password', 'password2'):
            raise forms.ValidationError("Passwords didn't match")

        return cleaned_data


class RecoverForm(forms.Form):
    locator = forms.CharField(label='Username or email')

    def clean_locator(self):
        value = self.cleaned_data.get('locator').lower()
        if not value:
            raise forms.ValidationError("This field is required")

        try:
            User.objects.get(Q(email=value) | Q(username=value))
            return value
        except User.DoesNotExist:
            raise forms.ValidationError("Username or email doesn't exists")


class PasswordResetForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(PasswordResetForm, self).clean()
        if not _validate_password_pair(cleaned_data, 'password', 'password2'):
            raise forms.ValidationError("Passwords didn't match")

        return cleaned_data

plf/main/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import login, authenticate

from main.models import User, Token
from main.forms import InvitationForm, RecoverForm, PasswordResetForm
from main.utils import send_mail, build_full_url


def get_token(uuid, ns):
    try:
        return get_object_or_404(Token, pk=uuid, tag__startswith=ns+'.')
    except Token.DoesNotExist:
        return None


def invitation(request, token):
    o = get_token(token, 'main.invitation')
    user = get_object_or_404(User, pk=o.locator)

    if request.method == 'POST':
        form = InvitationForm(request.POST)
    else:
        form = InvitationForm(initial={'token': token, 'email': user.email})

    if form.is_bound and form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.username = username
        user.is_active = True
        user.set_password(password)
        user.save()
        o.delete()

        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('front')

    else:
        return render(request, 'main/invite.html', {'form': form, 'token': token})


def reset(request, token):
    o = get_token(token, 'main.reset')
    user = get_object_or_404(User, pk=o.locator)

    form = PasswordResetForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'main/reset.html', {
            'form': form,
            'user': user})

    return HttpResponse('Password changed')


def recover(request):
    form = RecoverForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'main/recover.html', {'form': form})

    locator = form.cleaned_data.get('locator')

    u = User.objects.get(Q(email=locator) | Q(username=locator))

    token = Token(tag='main.reset.%s' % (u.id,))
    token.save()

    send_mail(u, 'reset', {
        'user': u,
        'reset_url': build_full_url(token.get_absolute_url())
    })

    return render_to_response('main/recover_done.html')


@csrf_exempt
def debug(request):
    if request.method == 'POST':
        import ipdb
        ipdb.set_trace()
    return render_to_response('main/debug.html')

plf/main/templates/main/debug.html
{% extends "base.html" %}
{% load staticfiles %}

{% block sitescripts %}
<script type="text/javascript">
	function run() {
	var v = [1,2];
	var fd = new FormData();
	$.each(v, function(idx, e) {
		fd.append('v', e);
	});
	$.ajax({
		url: '/plf/debug/',
		data: fd,
		contentType: false,
		processData: false,
		type: "POST",
		success: function () { window.alert('ok'); }
	});
}
</script>
{% endblock %}

{%block body %}
	<div data-role="page">
	<div data-role="content">
			<a href="#" onclick="run() ; return false;">Run</a>
	</div>
	</div>
{%endblock %}

plf/main/templates/main/form_non_field_errors.html
{% if form.non_field_errors %}
<p>Sorry, there is a problem:</p>
{# form.non_field_errors #}
{% endif %}

plf/main/templates/main/invite.html
{% extends "base.html" %}

{% block body %}

<div data-role="page" class="plf-small-page">
	<div data-role="header"><h2>{{site.name}}</h2></div>

	<div data-role="content">
		<strong>Choose your username and password and start sharing your stuff!</strong>

		{% include 'main/form_non_field_errors.html' with form=form only %}
		<form data-ajax="false" method="post" action="{% url 'main:invitation' token %}">
			{% csrf_token %}
			{{form.as_p}}
		
			<div class="plf-aside-left"><input type="submit" value="Go in!" /></div>
		</form>
	</div>
</div>

{% endblock %}

plf/main/templates/main/login.html
{% extends "base.html" %}

{% block body %}

<div data-role="page" class="plf-small-page">
	<div data-role="header"><h2>{{site.name}}</h2></div>

	<div data-role="content">
		{% include 'main/form_non_field_errors.html' with form=form only %}

		<form data-ajax="false" method="post" action="{% url 'main:login' %}">
			{% csrf_token %}
			{{ form.as_p }}
			{# FIXME: This URL is hardcoded #}
			<input type="hidden" name="next" value="{{ next|default:"/" }}" />
			<div class="plf-aside-left"><input type="submit" value="Log in" /></div>
		</form>
		<div class="plf-clear">

		<p class="plf-help">Help: <a href="{% url 'main:recover' %}">Do you forget your password (or username)?</a></p>
	</div>
</div>

{% endblock %}

plf/main/templates/main/recover.html
{% extends "base.html" %}

{% block body %}
<div data-role="page" class="plf-small-page">
	<div data-role="header"><h2>{{site.name}}</h2></div>

	<div data-role="content">
		{% include 'main/form_non_field_errors.html' with form=form only %}
		<form data-ajax="false" method="post" action="{% url 'main:recover' %}">
			{% csrf_token %}
			{{ form.as_p}}
			<div class="plf-aside-left"><input type="submit" value="Send me the details" /></div>
		</form>
	</div>
</div>

{% endblock %}

plf/main/templates/main/recover_done.html
{% extends "base.html" %}

{% block body %}
<div data-role="page" class="plf-small-page">
	<div data-role="header"><h2>{{site.name}}</div>
	<div data-role="content">An email has send to you with more instructions</div>
</div>
{% endblock %}

plf/main/templates/main/reset.html
{% extends "base.html" %}

{% block body %}

<div data-role="page" class="plf-small-page">
	<div data-role="header"><h2>{{site.name}</h2></div>

	<div data-role="content">
		{% include 'main/form_non_field_errors.html' with form=form only %}
		<form data-ajax="false" method="post" action="">
			{% csrf_token %}
			{{ form.as_p}}
			<input type="submit" value="Submit" />
		</form>
	</div>
</div>

{% endblock %}