plf/boards/urls.py
from django.conf.urls import patterns, url
from boards.views import BoardDetailView, BoardListView

urlpatterns = patterns(
    '',
    url(r'^$', BoardListView.as_view(), name='list'),
    url(r'^create/$', 'boards.views.create', name='create'),
    url(r'^(?P<pk>\d+)/$', BoardDetailView.as_view(), name='detail'),
    url(r'^(?P<board_id>\d+)/update/$', 'boards.views.update', name='update'),
    url(r'^(?P<board_id>\d+)/leave/$', 'boards.views.leave', name='leave'),
)

plf/plf/urls.py
from django.conf.urls import patterns, include, url

# static
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^albums/', include('photocms.urls', namespace="photocms")),
    url(r'^boards/', include('boards.urls', namespace="boards")),
    url(r'^plf/', include('main.urls', namespace="main")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', RedirectView.as_view(url=reverse_lazy('photocms:list')), name='front'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plf/boards/models.py
from django.core.urlresolvers import reverse
from django.db import models


from main.models import User
from main.utils import get_user_or_create_ghost


class Board(models.Model):
    name = models.CharField(max_length=128, blank=False, null=False, default=None)
    owner = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='boards')

    def __unicode__(self):
        return u"%s" % (self.name,)

    def get_absolute_url(self):
        return reverse('boards:detail', args=(self.id,))

    def is_owner(self, user):
        return self.owner == user

    def is_member(self, user):
        try:
            self.members.get(pk=user.id)
            return True
        except User.DoesNotExist:
            return False

    def save(self, *args, **kwargs):
        if not hasattr(self, 'members'):
            super(Board, self).save(*args, **kwargs)

        self.members.add(self.owner)
        super(Board, self).save(*args, **kwargs)

    def add_members_from_emails(self, emails):
        for u in [get_user_or_create_ghost(x) for x in emails]:
            self.members.add(u)

    def set_members_from_emails(self, emails):
        self.members = [get_user_or_create_ghost(x) for x in emails]

    def remove_members_from_ids(self, ids):
        for m in self.members.filter(id__in=ids):
            self.members.remove(m)

plf/boards/forms.py
import re

from django import forms
from django.forms import ModelForm

from main.utils import is_email

from boards.models import Board

class BoardForm(forms.Form):
    name = forms.CharField()
    members = forms.CharField(widget=forms.widgets.Textarea())

    def clean_members(self):
        value = self.cleaned_data.get('members')
        return [x for x in re.split(r'[\n\r,\s]+', value) if is_email(x)]

class BoardModelForm(ModelForm):
    class Meta:
        model = Board
        fields = ['name', 'members']

plf/boards/views.py
import re

from django.core.exceptions import PermissionDenied
from django.shortcuts import render, get_object_or_404, redirect

from django.utils.decorators import method_decorator

from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView, ListView
from django.views.generic.detail import DetailView


from main.utils import is_email
from boards.models import Board
from boards.forms import BoardForm


# FIXME: This should work as a mixin?
#class ProtectedView(TemplateView):
#    @method_decorator(login_required)
#    def dispatch(self, *args, **kwargs):
#        return super(ProtectedView, self).dispatch(*args, **kwargs)


class BoardListView (ListView):
    model = Board

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BoardListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return self.request.user.boards.all()

    def get_context_data(self, **kwargs):
        context = super(BoardListView, self).get_context_data(**kwargs)
        context.update({
            'form': BoardForm(),
            #'user': User.objects.get(pk=self.request.user.id),
        })
        return context


class BoardDetailView(DetailView):
    model = Board

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(BoardDetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BoardDetailView, self).get_context_data(**kwargs)

        board = kwargs.get('object')
        user = self.request.user

        if not board.is_member(self.request.user):
            raise PermissionDenied

        context.update({
            'board': board,
            'is_owner':  board.is_owner(user)
        })
        return context


@login_required
def create(request):
    form = BoardForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'boards/board_create.html', {'form': form})

    else:
        board = Board(owner=request.user, name=form.cleaned_data.get('name'))
        board.save()

        board.set_members_from_emails(form.cleaned_data.get('members'))
        board.save()

        return redirect(board.get_absolute_url())


@login_required
def update(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if not board.is_member(request.user):
        raise PermissionDenied

    if request.method != 'POST':
        return redirect(board.get_absolute_url())

    updated = {}

    updated_name = request.POST.get('name') or None
    if isinstance(updated_name, unicode) and board.name != updated_name:
        board.name = updated_name
        updated['name'] = updated_name

    added_members = []
    for t in request.POST.getlist('add_members') or []:
        added_members += [x for x in re.split(r'[\n\r\s,]+', t) if is_email(x)]

    if added_members and all([isinstance(x, unicode) for x in added_members]):
        board.add_members_from_emails(added_members)
        updated['added_members'] = added_members

    removed_members = request.POST.getlist('remove_members') or []

    if removed_members and all([isinstance(x, unicode) and x.isdigit() for x in removed_members]):
        board.remove_members_from_ids(removed_members)
        updated['removed_members'] = removed_members

    if updated:
        board.save()

    return redirect(board.get_absolute_url())


@login_required
def leave(request, board_id):
    board = get_object_or_404(Board, pk=board_id)
    if not board.is_member(request.user):
        raise PermissionDenied

    if request.user == board.owner:
        board.delete()
    else:
        board.members.remove(request.user)
    return redirect('boards:list')

plf/boards/templates/boards/board_create.html
{% extends "base.html" %}
{% load staticfiles %}

{%block body %}
	<!--
	#create
	Dialog page: Create a new board
	-->
	<div data-role="page" id="create">
	<div data-role="header"><h2>Create a new board</h2></div>
		<div data-role="content">
			<form id="form-create" data-ajax="false" action="{% url 'boards:create' %}" method="POST">
				{% csrf_token %}
				{{form.as_p}}
			
				{% include 'dialog-buttons.html' with form='form-create' ok_theme='b' ok_val='Create' %}
			</form>
		</div>
	</div>

{%endblock %}

plf/boards/templates/boards/board_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{%block body %}

<div data-role="page" id="board-{{board.id}}">
	{%include "header.html" %}
	<div data-role="content">
		<!-- Board metadata: title, icon, ... -->
		<h2>{{board.name}}</h2>

		<!-- Member list -->
		<ul data-role="listview" data-inset="true">
		{% for m in board.members.all %}
		<li>
			<h3>{{m.username}}</h3>
			<p>{% if m == board.owner %}Owner{% endif %}</p>

			{% if user == board.owner and m != user %}
			<form id="form-{{m.id}}" action="{% url 'boards:update' board.id %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="remove_members" value="{{m.id}}" />
			</form>
			<div style="width: auto;" class="ui-li-aside">
				<a href="#" data-role="button" data-icon="minus" data-theme="e" data-mini="true" onclick="
					$('form#form-{{m.id}}')[0].submit();
					return false;" >Remove</a>
			</div>
			{% endif %}
		</li>
		{% endfor %}
		</ul>

		<div class="plf-short" data-role="controlgroup"  data-type="horizontal">
			{% if is_owner %}
			<a  href="#add-members"
			    data-icon="plus" data-role="button" data-rel="dialog">Add friends</a>
			<a  href="#edit"
			    data-icon="edit" data-role="button" data-rel="dialog">Settings</a>
			{% endif %}
			<a href="#leave"
				data-icon="delete" data-role="button" data-rel="dialog">{{ is_owner|yesno:"Delete,Leave" }}</a>
			</a>
		</div>

	</div>
</div>

	<!--
	Page: Edit
	-->
	<div data-role="page" id="edit">
	<div data-role="header"><h2>Board settings</h2></div>
	<div data-role="content">
		<form id="form-edit" action="{% url 'boards:update' board.id %}" method="post">
			<label for="name-field">New name:</label>
			<input type="text" id="name-field" name="name" value="{{board.name}}" />
			{% csrf_token %}
		</form>
		{% include 'dialog-buttons.html' with form="form-edit" ok_theme="b" ok_val="Save" %}
	</div>
	</div>

	<!--
	Page: Add friends
	-->
	<div data-role="page" id="add-members">
	<div data-role="header"><h2>Add members</h2></div>
	<div data-role="content">
		<form id="form-add-members" action="{% url 'boards:update' board.id %}" method="post">
			{% csrf_token %}
			<textarea placeholder="Type some emails here…" name="add_members"></textarea>
		</form>
		{% include 'dialog-buttons.html' with form="form-add-members" ok_theme="b" ok_val="Add" %}
	</div>
	</div>

	<!--
	Page: delete
	-->
	<div data-role="page" id="leave">
	<div data-role="header"><h2>{{ is_owner|yesno:"Delete,Leave" }} this board?</h2></div>
	<div data-role="content">

		{% if is_owner %}
		<p><strong>Important:</strong>You are the owner of {{board.name}}.</p>
		<p>If you <strong>delete</strong> the board the other members will be unable to access board's albums</p>

		{% else %}

		<p>Are you sure to leave {{board.name}}?.</p>
		<p>You will be unable to access to the board albums</p>
		{% endif %}

		<form id="form-leave" action="{% url 'boards:leave' board.id %}" method="post">
			{% csrf_token %}
		</form>

		{% if is_owner %}
		{% include 'dialog-buttons.html' with form="form-leave" ok_theme="a" ok_val="Delete" %}
		{% else %}
		{% include 'dialog-buttons.html' with form="form-leave" ok_theme="a" ok_val="Leave" %}
		{% endif %}
	</div>
	</div>	

</div>


{%endblock %}

plf/boards/templates/boards/board_list.html
{% extends "base.html" %}
{% load staticfiles %}

{%block body %}
	<script type="text/javascript">
	function leaveBoard(id, name, is_owner) {
		var text = '';
		if (is_owner) {
			text = 'You are the owner of '+name+'.' + 
				'If you close the board the other members will be unable to access board\'s albums';
		}
		else {
			text = 'Are you sure to leave '+name+'?';
		}

		if (window.confirm(text)) {
			$('#form-'+id)[0].submit();	
		}
	}
	</script>

	<!--
	#list
	Main page: List all user boards
	-->
	<div data-role="page" id="list">
	{%include "header.html" %}

	<div data-role="content">

		{% if board_list %}
			<h2>{{user.username}}, your boards:</h2>

			<ul data-role="listview" data-inset="true">
				{% for br in board_list %}
				<li>{% include 'boards/board_preview.html' with board=br user=user only %}</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>You aren't member of any board. May be you should create a new one.</p>
		{% endif %}

		<div class="plf-aside-left">
			<a data-role="button" data-icon="plus" href="#create" data-rel="dialog">Create a new board</a>
		</div>
	</div>
	</div>


	<!--
	#create
	Dialog page: Create a new board
	-->
	<div data-role="page" id="create">
	<div data-role="header"><h2>Create a new board</h2></div>
		<div data-role="content">
			<form id="form-create" data-ajax="false" action="{% url 'boards:create' %}" method="POST">
				{% csrf_token %}
				{{form.as_p}}
			
				{% include 'dialog-buttons.html' with form='form-create' ok_theme='b' ok_val='Create' %}
			</form>
		</div>
	</div>

{%endblock %}

plf/boards/templates/boards/board_preview.html
<a href="{% url 'boards:detail' board.id %}"> 
	<div class="ui-li-heading">{{ board.name}}</div>
	<p class="ui-li-desc">{% if board.owner == user %}Owner{% else %}Member{% endif %}</p>
	<p class="ui-li-desc">
		Latest albums: {% for album in board.albums.all|slice:"3" %}
		{{album.name}}
		{% endfor %}
	</p>
</a>

plf/boards/templates/boards/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{%block body %}
<script type="text/javascript">

function leaveBoard(id, name, is_owner) {
	var text = '';
	if (is_owner) {
		text = 'You are the owner of '+name+'.' + 
			'If you close the board the other members will be unable to access board\'s albums';
	}
	else {
		text = 'Are you sure to leave '+name+'?';
	}

	if (window.confirm(text)) {
		$('#form-'+id)[0].submit();
	}
}
</script>

<div data-role="page" id="board-{{board.id}}">
	{%include "header.html" %}
	<div data-role="content">
		<!-- Board metadata: title, icon, ... -->
		<h2>{{board.name}}</h2>

		<!-- Member list -->
		<ul data-role="listview" data-inset="true">
		{% for m in board.members.all %}
		<li>
			<h3>{{m.username}}</h3>
			<p>{% if m == board.owner %}Owner{% endif %}</p>

			{% if user == board.owner and m != user %}
			<form id="form-{{m.id}}" action="{% url 'boards:update' board.id %}" method="post">
				{% csrf_token %}
				<input type="hidden" name="remove_members" value="{{m.id}}" />
			</form>
			<div style="width: auto;" class="ui-li-aside">
				<a href="#" data-role="button" data-icon="minus" data-theme="e" data-mini="true" onclick="
					$('form#form-{{m.id}}')[0].submit();
					return false;" >Remove</a>
			</div>
			{% endif %}
		</li>
		{% endfor %}
		</ul>

		<div class="plf-short" data-role="controlgroup"  data-type="horizontal">
			{% if is_owner %}
			<a  href="#board-members-add"
			   data-mini="true" data-icon="plus" data-role="button" data-rel="dialog">Add more members</a>
			<a  href="#board-name-edit"
			   data-mini="true" data-icon="edit" data-role="button" data-rel="dialog">Ajustes</a>
			{% endif %}

			<a data-icon="delete" data-role="button" data-mini="true" href="{% url 'boards:leave' board.id %}">
			{{ is_owner|yesno:"Delete,Leave" }}
			</a>
		</div>

	</div>
</div>


<div data-role="page" id="board-name-edit">
	<div data-role="header"><h2>Change name</h2></div>
	<div data-role="content">
		<form id="title-edit-form" action="{% url 'boards:update' board.id %}" method="post">
			{% csrf_token %}
			<input id="name-edit-field" type="text" value="{{board.name}}" name="name"></textarea>
		</form>
		<a data-role="button" data-theme="b" href="#" onclick="$('form#title-edit-form')[0].submit(); return false;">Save</a>
	</div>
</div>

<div data-role="page" id="board-members-add">
	<div data-role="header"><h2>Add members</h2></div>
	<div data-role="content">
		<form id="add-members" action="{% url 'boards:update' board.id %}" method="post">
			{% csrf_token %}
			<textarea placeholder="Type some emails here…" name="add_members"></textarea>
		</form>
		<a data-role="button" data-theme="b" href="#" onclick="$('form#add-members')[0].submit(); return false;">Add</a>
	</div>
</div>


{%endblock %}

plf/boards/templates/boards/list.html
{% extends "base.html" %}
{% load staticfiles %}

{%block body %}
	<script type="text/javascript">
	function leaveBoard(id, name, is_owner) {
		var text = '';
		if (is_owner) {
			text = 'You are the owner of '+name+'.' + 
				'If you close the board the other members will be unable to access board\'s albums';
		}
		else {
			text = 'Are you sure to leave '+name+'?';
		}

		if (window.confirm(text)) {
			$('#form-'+id)[0].submit();	
		}
	}
	</script>

	<!--
	#boards
	Main page: List all user boards
	-->
	<div data-role="page" id="boards">
	{%include "header.html" %}
	<div data-role="content">
		<h2>{{user.username}}, your boards:</h2>


		<ul data-role="listview" data-inset="true">
		{% for br in boards %}
		<li>
			<a href="{% url 'boards:detail' br.id%}">
				<h3 class="ui-li-heading">{{ br.name}}</h3>
				<p class="ui-li-desc">{% if br.owner == user %}Owner{% else %}Member{% endif %}</p>
			</a>
		</li>
		{% endfor %}
		</ul>

		<a class="plf-short" data-mini="true" data-role="button" data-icon="plus" href="#board-new" data-rel="dialog">Create new board</a>
	</div>
	</div>


	<!--
	#board-new
	Dialog page: Create a new board
	-->
	<div data-role="page" id="board-new">
	<div data-role="header"><h2>New board</h2></div>
		<div data-role="content">
			<form id="form-board-new" data-ajax="false" action="{% url 'boards:new' %}" method="POST">
				{% csrf_token %}
				{{form.as_table}}
			
			<div class="ui-grid-a">
				<div class="ui-block-a"><a data-role="button" href="#" data-rel="back">Cancel</a></div>
				<div class="ui-block-b"><input data-theme="b" type="submit" value="Create" /></div>
			</div>
			</form>
		</div>
	</div>

{%endblock %}

plf/boards/templates/boards/new.html
{% extends "base.html" %}
{% load staticfiles %}

{%block body %}
<script type="text/javascript">
function submitForm(id, prefix) {
	if (typeof(prefix) === undefined) {
		prefix = 'form-';
	}

	$('#' + prefix + id)[0].submit();
	return false;
}
</script>

<div data-role="page" id="board-{{board.id}}">
	{%include "header.html" %}
	<div data-role="content">
		<form action="{% url 'boards:new' %}" method="POST">
			{% csrf_token %}
			{{form.as_table}}
			<input type="submit" value="Create" />
		</form>
	</div>
</div>
{%endblock %}