plf/photocms/urls.py
from django.conf.urls import patterns, url

from photocms import views

urlpatterns = patterns(
    '',
    url(r'^$', views.AlbumListView.as_view(), name='list'),
    url(r'^upload(/(?P<album_id>\d+))?', views.api_album_update, name='upload'),
    url(r'^detail/(?P<pk>\d+)/$', views.AlbumDetailView.as_view(), name='detail'),
    url(r'^share/(?P<album_id>\d+)$', views.api_album_update, name='share'),
    url(r'^(?P<album_id>\d+)/delete$', views.api_album_delete, name='delete'),

    # CRUD API
    #url(r'^_/update(/(?P<album_id>\d+))?', views.api_album_update, name='api_album_update'),
    #url(r'^_/list', views.api_album_list, name='api_album_list'),
    #url(r'^_/(?P<album_id>\d+)', views.api_album_detail, name='api_album_detail'),
)

plf/plf/urls.py
from django.conf.urls import patterns, include, url

# static
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^albums/', include('photocms.urls', namespace="photocms")),
    url(r'^boards/', include('boards.urls', namespace="boards")),
    url(r'^plf/', include('main.urls', namespace="main")),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', RedirectView.as_view(url=reverse_lazy('photocms:list')), name='front'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plf/photocms/models.py
from hashlib import sha1
from os import makedirs, rmdir, unlink, listdir
from os.path import join, basename, dirname, splitext
from random import sample
from re import subn
from time import mktime
from zipfile import ZipFile

from django.core.files.storage import default_storage
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save, pre_delete, pre_save
from django.dispatch import receiver


from sorl.thumbnail import ImageField, delete as sorl_delete


from main.models import User
from boards.models import Board
from photocms import get_profiled_thumbnail


class Album(models.Model):
    name = models.CharField(max_length=255, null=False, default=None, blank=False)
    pub_date = models.DateTimeField('date published', auto_now=True)
    last_update = models.DateTimeField('last update', auto_now=True)
    owner = models.ForeignKey(User, related_name='albums', null=False, on_delete=models.CASCADE)
    boards = models.ManyToManyField(Board, related_name='albums', null=False)
    updated = True

    # Django methods

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photocms:detail', args=[self.id])

    # Extra properties

    # FIXME: Find better way
    @property
    def as_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'owner': self.owner.id,
            'owner_username': self.owner.username,
            'archive': self.archive_url,
            'cover': self.cover.file.url if self.cover else '',
            'url': self.get_absolute_url(),
            'pub_date': mktime(self.pub_date.utctimetuple()),
            'items': [i.as_dict for i in self.items.all()]
            }

    @property
    def folder(self):
        return default_storage.path(join('photos', str(self.id)))

    @property
    def archive_name(self):
        return 'zips/' + str(self.id) + '/' + subn(r'[^a-zA-Z0-9_ \-]', '_', self.name)[0] + ".zip"

    @property
    def archive_path(self):
        return default_storage.path(self.archive_name)

    @property
    def archive_url(self):
        return default_storage.url(self.archive_name)

    @property
    def cover(self):
        try:
            return self.items.all()[0]
        except IndexError:
            return None

    #
    # get_cover and get_sample are methods and not properties because they
    # can return (and probably they will) diferent results
    #

    def get_cover(self):
        self.get_sample()

        try:
            return self._sample[0]
        except IndexError:
            return None

    def get_sample(self, m=4):
        try:
            return self._sample[1:]

        except AttributeError:
            items = self.items.all()
            if len(items) < m+1:
                self._sample = (items[0],)
            else:
                self._sample = sample(items, m+1) 

            return self._sample[1:]

    #
    # Update for CRUD
    #
    def update(self, data):
        name = data.get('name')
        if name:
            self.updated = True
            self.name = name

        files_added = data.get('files_added')
        if files_added:
            for upload in files_added:
                Item(album=self, file=self._handle_file(upload)).save()
            self.updated = True

        files_removed = data.get('files_removed')
        if files_removed:
            for item in Item.objects.filter(pk__in=files_removed, album=self):
                item.delete()
            self.updated = True

    #
    # Init and cleanup filesystem
    #
    def init_fs(self):
        makedirs(self.folder)
        makedirs(dirname(self.archive_path))

    def cleanup_fs(self):
        # Remove album folder
        rmdir(self.folder)

        # Remove zip stuff
        zipdir = dirname(default_storage.path(self.archive_name))
        for f in [zipdir+"/"+e for e in listdir(zipdir)]:
            unlink(f)
        rmdir(zipdir)

    #
    # Checking access
    #
    def user_can_access(self, user):
        if user.is_anonymous():
            return False

        if self.owner == user:
            return True

        album_set = set(self.boards.all())
        user_set = set(user.boards.all())

        if album_set.intersection(user_set):
            return True
        else:
            return False

    def user_can_edit(self, user):
        if user.is_anonymous():
            return False

        if self.owner == user:
            return True

    #
    # Other methods
    #
    def create_archive(self):
        zipdirname = dirname(self.archive_path)
        for f in [zipdirname + "/" + e for e in listdir(zipdirname)]:
            unlink(f)

        zip = ZipFile(self.archive_path, 'w')
        for (i, item) in enumerate(self.items.all()):
            zip.write(item.file.path, "%s/%04d_%s" % (self.name, i+1, basename(item.file.name)))
        zip.close()


def _upload_handler(item, filename):
    digest = sha1()
    for chunk in item.file.chunks():
        digest.update(chunk)

    hexdig = digest.hexdigest()
    return default_storage.get_available_name(
        'photos/%d/%s%s' % (item.album.id, hexdig, splitext(filename)[1])
        )


class Item(models.Model):
    album = models.ForeignKey('Album', related_name='items', null=False, on_delete=models.CASCADE)
    file = ImageField(upload_to=_upload_handler, null=False)

    # FIXME: Find better way
    @property
    def as_dict(self):
        return {
            'id': self.id,
            'url': self.file.url,
            }

    @property
    def thumbnail(self):
        return get_profiled_thumbnail(self.file, 'square')

    @property
    def medium(self):
        return get_profiled_thumbnail(self.file, 'medium')


@receiver(post_save, sender=Album)
def album_post_save(sender, **kwargs):
    album = kwargs.get('instance')
    created = kwargs.get('created')

    if created:
        album.init_fs()

    if album.updated:
        album.create_archive()

    album.updated = False


@receiver(pre_delete, sender=Album)
def album_pre_delete(sender, **kwargs):
    kwargs.get('instance').cleanup_fs()


@receiver(pre_save, sender=Item)
def item_pre_save(sender, **kwargs):
    item = kwargs.get('instance')

    if not item.file:
        raise Exception("file can't be null")


@receiver(pre_delete, sender=Item)
def item_pre_delete(sender, **kwargs):
    sorl_delete(kwargs.get('instance').file)

plf/photocms/views.py
import json
import datetime

from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from photocms.models import Album, Item


from django.views.generic import ListView
from django.views.generic.detail import DetailView

import logging

_logger = logging.getLogger('plf.user')


class AlbumListView (ListView):
    model = Album

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        _logger.info('%s:photocms.index' % (self.request.user,))
        return super(AlbumListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Album.objects.filter(boards__in=self.request.user.boards.all()).order_by('-pub_date').distinct()

    # Handle AJAX as well?
        #ret = {
        #    'code': '0',
        #    'msg': 'success',
        #    'albums': []
        #}
        #
        #for album in albums:
        #    ret['albums'].append({
        #        'id': album.id,
        #        'url': album.get_absolute_url(),
        #        'name': album.name,
        #        'cover': album.cover.file.url if album.cover else '',
        #        'nitems': len(album.items.all())
        #        })
        #
        #return HttpResponse(json.dumps(ret), mimetype='application/json')


class AlbumDetailView(DetailView):
    model = Album

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        _logger.info('%s:photocms.detail.%s %s' % (self.request.user, kwargs['pk'], self.get_object()))
        return super(DetailView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(AlbumDetailView, self).get_context_data(**kwargs)

        user = self.request.user
        album = kwargs['object']
        if not album.user_can_access(user):
            raise PermissionDenied

        operations = []
        if album.user_can_access(user):
            operations.append('access')
        if album.user_can_edit(user):
            operations.append('edit')
        if album.owner == user:
            operations = ('access', 'edit', 'all')

        context.update({
            'operations': operations
            })
        return context

    # Handle ajax
        #return HttpResponse(json.dumps({
        #    'code': 0,
        #    'msg': 'ok',
        #    'operations': operations,
        #    'album': album.as_dict
        #}), mimetype='application/json')


#
# CRUD: Update
#
@login_required
@csrf_exempt
def api_album_update(request, album_id):
    def _is_valid_email(s):
        if (not s) or ('@' not in s[1:-1]):
            return False

        (u, d) = s.split('@')
        if not all([u, d, '.' in d[:-2]]):
            return False

        return True

    if request.method == 'POST':
        opts = {}
        opts['id'] = album_id
        opts['name'] = request.POST.get('name')
        opts['files_added'] = request.FILES.getlist('files_added') or []
        opts['grant_access'] = request.POST.getlist('grant_access') or []

        updated = False
        rebuild_archive = True

        if opts['id']:
            album = get_object_or_404(Album, pk=opts['id'])
        else:
            album = Album(owner=request.user, name=(opts['name'] or 'Untitled'))
            album.save()  # Needed to get the id
            updated = True
            rebuild_archive = False

        if opts['name'] and opts['name'] != album.name:
            album.name = opts['name']
            updated = True
            rebuild_archive = False

        iids = []
        for upload in opts['files_added']:
            item = Item(album=album, file=upload)
            item.save()
            iids.append(item.id)
            updated = True
            rebuild_archive = False


        # FIXME: There are better ways to do this

        # Filter input parameter to adjust to user boards
        boards = request.user.boards.filter(pk__in=request.POST.getlist('boards'))
        b_add = [b for b in boards if b not in album.boards.all()]
        b_del = [b for b in album.boards.all() if b not in boards]

        for b in b_add:
            album.boards.add(b)
        for b in b_del:
            album.boards.remove(b)


        if updated:
            album.last_update = datetime.datetime.now()
            album.save()

        if rebuild_archive:
            album.create_archive()

        if request.is_ajax():
            return HttpResponse(json.dumps({
                'code': '0',
                'msg': 'success',
                'items_added': iids,
                'album': album.as_dict
                }), mimetype='application/json')
        else:
            return HttpResponseRedirect(reverse('photocms:detail', args=(album.id,)))

    else:
        return render(request, "photocms/upload.html")


#
# CRUD: Delete
#

@login_required
# @csrf_exempt
def api_album_delete(request, album_id):
    if request.method != 'POST':
        return HttpResponse(json.dumps({'code': '1', 'msg': 'Only POST allowed'}), mimetype='application/json')

    album = get_object_or_404(Album, pk=album_id)
    aid = album.id
    album.delete()

    if request.is_ajax():
        return HttpResponse(json.dumps({
            'code': '0',
            'msg': 'success',
            'id': aid,
        }), mimetype='application/json')

    else:
        return HttpResponseRedirect(reverse('photocms:list'))

plf/photocms/templates/photocms/album_boards_edit.html
<fieldset data-role="controlgroup">
	<legend><h2>Share with:</h2></legend>
	{% for gr in available %}
	<label for="board-{{gr.id}}">{{gr.name}}</label>
	<input type="checkbox" name="boards" class="board-checkbox" id="board-{{gr.id}}" value="{{gr.id}}"
		{% if gr in enabled %} checked {% endif %} />
	{% endfor %}

	<div class="plf-help" id="private-post-alert">If no boards are selected the post will be private and nobody except you will see it</div>
</fieldset>

plf/photocms/templates/photocms/album_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbs %}

{% block sitestylesheets %}
<link rel="stylesheet" href="{% static "photoswipe-3.0.5/photoswipe.css" %}" />
{% endblock %}

{% block sitescripts %}
<script type="text/javascript" src="{% static "photoswipe-3.0.5/lib/klass.min.js" %}" ></script>
<script type="text/javascript" src="{% static "photoswipe-3.0.5/code.photoswipe.jquery-3.0.5.min.js" %}" ></script>
<script type="text/javascript">
$('#detail').live('pageinit', function () {
	$.mobile.ajaxEnabled = false;
	var myPhotoSwipe = $(".album-item a").photoSwipe({ enableMouseWheel: false , enableKeyboard: true});
});
</script>
{%endblock%}

{%block body %}
	<div data-role="page" id="detail">
	{%include "header.html" %}
	<div data-role="content">
	
		<div class="album">

			<div class="ui-grid-a album-header">
				<div class="ui-block-a album-cover-wrap"><img src="{{album.cover.file|thumb:'square'}}" /></div>
				<div class="ui-block-b">
					<h2 class="album-title">{{album.name}}</h2>
					<div class="album-owner">{{album.owner.username}} - {{album.pub_date}}</div>
				</div>
			</div>

			<div class="album-operations" data-role="controlgroup" data-mini="true" data-type="horizontal">
				{% if 'access' in operations %} <a data-icon="arrow-d" data-role="button" href="{{album.archive_url}}">Download</a> {% endif %}
				{% if '-edit' in operations %} <a data-icon="plus" data-role="button" href="">Upload</a> {% endif %}
				{% if '-edit' in operations %} <a data-icon="edit" data-role="button" href="{% url 'photocms:edit' album.id %}">Edit</a> {% endif %}
				{% if 'all' in operations %} <a data-icon="forward" data-role="button" data-rel="dialog" href="#share">Share</a> {% endif %}
				{% if 'all' in operations %} <a data-icon="delete" data-role="button" data-rel="dialog" href="#delete">Delete</a> {% endif%}
			</div>


			<div class="ui-grid-c album-items">
			{% for item in album.items.all %}
				<div class="ui-block-{% cycle 'a' 'b' 'c' 'd' %} album-item">
					<div class="plf-image-link-wrapper"><a href="{{item.file|thumb:'medium'}}"><img src="{{item.file|thumb:'square'}}" /></a></div>
				</div>
			{% endfor %}
			</div>
		</div>
	
	</div>
	</div>

	<!--
	Page: share
	-->
	<div data-role="page" id="share" >
	<div data-role="header"><h2>Share `{{album.name}}'</h2></div>
	<div data-role="content">
		<form method="POST" id="form-share" action="{% url "photocms:share" album.id %}">
		{% csrf_token %}
		{% include "photocms/album_boards_edit.html" with available=user.boards.all enabled=album.boards.all %}
		</form>

		{% include "dialog-buttons.html" with form="form-share" ok_theme="b" ok_val="Share" only %}
	</div>
	</div>

	<!--
	Page: Delete
	-->
	<div data-role="page" id="delete" >
	<div data-role="header"><h2>Delete album `{{album.name}}'?</h2></div>
	<div data-role="content">
		<p>All photos and videos will be erased, friends with access permission will also lost access to them.<br />
	    This action <strong>can't</strong> be undone</p>

	    <form id="form-delete" action="{% url 'photocms:delete' album.id%}" method="POST" data-ajax="false" >
		{% csrf_token %}
	    </form>

		{% include "dialog-buttons.html" with form="form-delete" ok_theme="a" ok_val="Delete. I'm sure" only %}
	</div>
	</div>

{%endblock %}

plf/photocms/templates/photocms/album_list.html
{% extends "base.html" %}

{% block body %}
	<!--
	Index page
	-->
	<div id="page-list" data-role="page">
	{%include "header.html" with user=user %}
	<div data-role="content">

		{% if album_list %}
			<ul id="album-index-listview" data-role="listview" data-inset="true" data-filter="true">
			{% for album in album_list %}
				<li>
					{% include 'photocms/album_preview.html' with album=album only %}	
				</li>
			{% endfor %}
			</ul>
		{% else %}
		<p>Ups, there is nothing to show</p>
		{% endif %}
	</div>
	</div>
{% endblock %}

plf/photocms/templates/photocms/album_preview.html
{% load thumbs %}

<!-- Rich content for desktop -->
<!--
<div class="post-preview">
	<h2 class="title"><a href="{{album.get_absolute_url}}">{{album.name}}</a></h2>
	<div class="post-meta">
		Posted by {{album.owner.username}} on {{album.pub_date}}
	</div>


	<div class="album-cover">
		<img src="{{album.get_cover.file|thumb:'wide'}}" />
	</div>

	<div class="ui-grid-c album-mosaic">
		{% for s in album.get_sample|slice:"4" %}
		<div class="ui-block-{% cycle 'a' 'b' 'c' 'd' %}"><img src="{{s.file|thumb:'square'}}" /></div>
		{% endfor %}
	</div>
</div>
-->

<!-- Bandwidth friendly version -->
<a href="{{album.get_absolute_url}}">
	<img class="ui-li-thumb" width="200px" src="{{album.cover.file|thumb:'square'}}" />
	<div class="ui-li-heading">{{album.name}}</div>
	<p class="ui-li-count">{{album.items.all|length}} items</p>
</a>

plf/photocms/templates/photocms/edit.html
{% extends "base.html" %}
{% load thumbnail %}

{% block title %}{{album.name}}{% endblock %}

{% block content %}
	<h1>Edit `{{ album.name}}'</h1>

	<form data-ajax="false" method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}



	<!-- Add more photos -->
	<label for="files">Add more images</label>
	<input type="file" name="files" accept="image/*" multiple="true" />
	
	<!-- Remove photos from current album -->
	<div class="thumbnails_wrapper" data-role="controlgroup">
	{% for item in album.items.all %}
		{% thumbnail item.file "200x200" crop="center" as th %}
		<label for="deleted-{{item.id}}"><img src="{{ th.url }}" /></label>
		{% endthumbnail %}
		<input type="checkbox" id="deleted-{{item.id}}" name="deleted-{{item.id}}" />
		<!-- <div class="state button" id="state-{{item.id}}">Keep/Reject</div> -->
	{% endfor %}
	</div>

	<input type="submit" value="Save" />
	</form>


{% endblock %}

plf/photocms/templates/photocms/upload.html
{% extends "base.html" %}
{% load staticfiles %}

{% block sitescripts %}
	<script src="{% static "upload.js" %}"></script>
	<script src="{% static "utils.js" %}"></script>

	<script type="text/javascript">


	function render(src, listViewItem) {
		var img = listViewItem.find('img')[0];
		img.onload = function () {
/*
			var src_x; var src_y;
			var src_w; var src_h;

			var min_ = Math.min(img.width, img.height);
	       		if (img.width > min_) {
				src_x = (img.width - min_) / 2;
				src_y = 0;
				src_w = min_;
				src_h = img.height;
			}
			else {
				src_x = 0;
				src_y = (img.height - min_) / 2;
				src_w = img.width;
				src_h = min_;
			}
*/

			var canvas = $('<canvas>').attr('width', '80px').attr('height', '80px')[0];
			var ctx = canvas.getContext('2d');
			ctx.clearRect(0, 0, canvas.width, canvas.height);
			ctx.drawImage(img, 0, 0, img.width, img.height);
			img.onload = undefined;
			
/*
			ctx.drawImage(img,
				src_x, src_y,
				src_w, src_h,
				0, 0,
				canvas.width, canvas.height);
*/
			img.src = canvas.toDataURL();
		}
		img.src = src;
	}

	function loadImage(src, listViewItem) {
		var reader = new FileReader();
		reader.onload = function (ev) {
			render(ev.target.result, listViewItem);
		}
		reader.readAsDataURL(src);
	}

	function itemizeFile(file) {
		var html = '' +
			'<li class="ui-li-static">' +
		//	'   <img width=80px height=80px >' +
			'	<h2>'+file.name+'</h2>' + 
			'	<p class="upload-progress">'+humanizeSize(file.size)+'</p>' + 
			'</li>';
		var listViewItem = $(html);

		// loadImage(file, listViewItem);

		return listViewItem;
	}

	var loadingFilesTimeout = undefined;
	function onLoadFilesBegin() {
		window.loadingFilesTimeout = window.setTimeout(function() {
			$.mobile.changePage('#loading');
			loadingFilesTimeout = undefined;
		}, 3 * 1000);		
	}

	function onLoadFilesEnd() {
		if (loadingFilesTimeout) {
			window.clearTimeout(loadingFilesTimeout);
			loadingFilesTimeout = undefined;
		}		
		else {
			$.mobile.changePage('#main');

		}
		var nuploads = $('#upload-listview').find('.ui-li').length;
		$('#upload-listview-resume').html(nuploads+' files are ready for upload');
	}

	function onProgress(ev, file) {
		var percent = Math.min(
			Math.round((ev.loaded / ev.total) * 100),
			100);

		window.uploadApp
			.getListViewItemForFile(file)
			.find('.upload-progress')
			.html('<p>Uploaded '+percent+'% of '+humanizeSize(file.size)+'</p>');
	}


	function onItemCompleted(file) {
	}


	function onUploadCompleted(file) {
		window.location.replace(window.uploadApp.album.url);
	}

	$('#main').live('pageinit', function () {
		window.uploadApp = new Upload({
			'endPoint'          : '{%url 'photocms:upload' %}',
			'listView'          : $('#upload-listview'),
			'fileFieldsWrapper' : $('#upload-filefields-wrapper'),

			'itemizeFile'       : itemizeFile,
			'onLoadFilesBegin'  : onLoadFilesBegin,
			'onLoadFilesEnd'    : onLoadFilesEnd,
			'onProgress'        : onProgress,
			'onItemCompleted'   : onItemCompleted,
			'onUploadCompleted' : onUploadCompleted,
			'onFormBuild' : function(formdata) {
				formdata.append('name', $('#upload-name').val());
				$.each($('input[name=boards]:checked'), function(idx, e) {
					formdata.append('boards', $(e).val());
				});
				/* FIXME: For reference, this parameters will be userful 
				'extraParams' : {
					'csrf_token': '{{ csrf_token }}',
					'csrf_name': 'csrfmiddlewaretoken',
					'csrf_xname': 'X-CSRFToken',
				},
				*/
			},

		}).init();
	});

   function doUpload() {
       if ($('input[name=boards]:checked').length > 0) {
           window.uploadApp.upload();
       } else {
           $.mobile.changePage('#warning');
       } 
   }


	</script>
<style>
</style>
{% endblock %}


{%block body %}
	<div data-role="page" id="main">
	{%include "header.html" %}
	<div data-role="content">

	<div id="uploader">

		<label for="upload-name"><h2>Name:</h2></label>
		<input id="upload-name" type="text" name="name" />

		{% include "photocms/album_boards_edit.html" with available=user.boards.all only %}


		<div id="upload-listview-wrap">
		<h2>Files:</h2>
		<div data-role="collapsible" data-theme="" data-content-theme="c">
		    <h4><div id="upload-listview-resume">Heading</div></h4>
		    <ul id="upload-listview" data-role="listview"></ul>
		</div>
		</div>

		<div class="plf-pseudo-hidden" id="upload-filefields-wrapper">
		</div>

		<div id="actions-wrapper" data-role="controlgroup" data-type="horizontal">
			<a id="upload-append-button" href="#"
			   data-role="button" data-icon="plus" >Select photos</a>		
			<a id="upload-button" onclick="doUpload(); return false;" href="#"
			   data-role="button" data-icon="arrow-u">Upload</a>
		</div>

	</div>

	</div>
	</div>


	<!--
	Dialog: warning
	-->
	<div data-role="dialog" id="warning">
	<div data-role="header"><h2>There is a problem!</h2></div>
	<div data-role="content">
		<p>Uops, you didn't select any boards to share with!</p>
		<p>You must select at least one board</p>
		<a data-role="button" href="#" data-rel="back">Go back</a>
	</div>
	</div>


	<!--
	Dialog: upload
	-->
	<div data-role="dialog" id="loading" data-close-btn="none">
	<div data-role="header"><h2>Please wait</h2></div>
	<div data-role="content">
		<p>Your device is loading selected files.</p>
		<p>Anyway, you can close this window safely</p>
		<div class="plf-help">Depending of the device and the number and size of files this can take from seconds to few minutes. Please be patient</p></div>
	</div>
	</div>



<script type="text/javascript">
function syncUi () {
	if ($('#upload-listview').find('li').length) {
		$('#upload-listview-wrap').show();
		$('#upload-button').show();
		$('#actions-wrapper').controlgroup();
	}
	else {
		$('#upload-listview-wrap').hide();
		$('#upload-button').hide();
		// Using controlgroup inmediatly has no efect
		setTimeout(function () {
			$('#actions-wrapper').controlgroup();
		}, 1);
	}
}

function onBoardCheckboxChange (ev) {
c.change(function () { console.log(arguments); });
}

$('#upload-append-button').live('click', 'button',function() {
    $('.current-filefield').find('input[type=file]').click();
});

$('input[type=file]').live('change', syncUi);

syncUi();


</script>


{% endblock %}